name: Expo actions
on:
  push:
    branches:
      - master
jobs:
  Publish_Updates:
    name: Install and publish
    if: "contains(github.event.head_commit.message, '[Release]')" # If commit message contains "[Released]" only then this job would be run.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install
      - run: expo publish
  GenerateNewBuild:
    name: Build new artifact
    runs-on: ubuntu-latest
    needs: Publish_Updates
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install
      - run: expo build:android -t apk > ./build_status.txt
      - name: Upload result for building job
        uses: actions/upload-artifact@v2
        with:
          name: build_status
          path: ./build_status.txt
  ShowBuildResult:
    name: Show results
    runs-on: ubuntu-latest
    needs: GenerateNewBuild
    steps:
      - name: Download result for building job
        uses: actions/download-artifact@v2
        with:
          name: build_status
      - name: Print result for building job
        shell: bash
        run: |
          value=`cat ./build_status.txt`
          echo $value | grep "expo.io/artifacts"